/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/menu/{restaurant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Unique UFDS restaurant identifier.
                 * @example RST-IN-MH-001
                 */
                restaurant_id: components["parameters"]["restaurantId"];
            };
            cookie?: never;
        };
        /**
         * Fetch full menu
         * @description Returns the complete UFDS-normalised menu for the restaurant.
         */
        get: operations["getMenu"];
        /**
         * Replace entire menu
         * @description Replaces the restaurant's full menu and fans the update out to all
         *     connected delivery platforms via their respective adapters.
         */
        put: operations["replaceMenu"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/menu/{restaurant_id}/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Unique UFDS restaurant identifier.
                 * @example RST-IN-MH-001
                 */
                restaurant_id: components["parameters"]["restaurantId"];
                /**
                 * @description Menu item identifier.
                 * @example ITEM-001
                 */
                item_id: components["parameters"]["itemId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove a menu item
         * @description Permanently removes the item from the menu and all connected platforms.
         */
        delete: operations["deleteMenuItem"];
        options?: never;
        head?: never;
        /**
         * Update a single menu item
         * @description Partially update one item (price, availability, description, etc.).
         */
        patch: operations["updateMenuItem"];
        trace?: never;
    };
    "/orders/{restaurant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Unique UFDS restaurant identifier.
                 * @example RST-IN-MH-001
                 */
                restaurant_id: components["parameters"]["restaurantId"];
            };
            cookie?: never;
        };
        /**
         * List orders
         * @description Returns a paginated list of orders. Filterable by status, platform,
         *     and date range. Results are sorted by `placed` timestamp descending.
         */
        get: operations["listOrders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{restaurant_id}/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Unique UFDS restaurant identifier.
                 * @example RST-IN-MH-001
                 */
                restaurant_id: components["parameters"]["restaurantId"];
                /**
                 * @description UFDS canonical order ID.
                 * @example UFDS-ORD-20260616-00142
                 */
                order_id: components["parameters"]["orderId"];
            };
            cookie?: never;
        };
        /**
         * Fetch a single order
         * @description Returns the full UFDS Order Object for the given order ID.
         */
        get: operations["getOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update order status
         * @description Transitions the order to a new status. UFDS validates the transition
         *     (e.g. cannot go from `DELIVERED` back to `PREPARING`) and propagates
         *     the update to the originating platform via its adapter.
         *
         *     Valid transitions:
         *     - `PENDING` → `ACCEPTED` or `CANCELLED`
         *     - `ACCEPTED` → `PREPARING` or `CANCELLED`
         *     - `PREPARING` → `READY` or `CANCELLED`
         *     - `READY` → `PICKED_UP` or `CANCELLED`
         *     - `PICKED_UP` → `DELIVERED`
         */
        patch: operations["updateOrderStatus"];
        trace?: never;
    };
    "/orders/{restaurant_id}/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Unique UFDS restaurant identifier.
                 * @example RST-IN-MH-001
                 */
                restaurant_id: components["parameters"]["restaurantId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inject a test order (sandbox only)
         * @description Available in the **sandbox environment only**. Injects a synthetic order
         *     to test your webhook handler and order lifecycle integration without
         *     any real platform involvement.
         */
        post: operations["simulateOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/{restaurant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Unique UFDS restaurant identifier.
                 * @example RST-IN-MH-001
                 */
                restaurant_id: components["parameters"]["restaurantId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk availability update
         * @description Push availability changes for multiple items in one call.
         *     UFDS fans the update out to all connected platforms simultaneously.
         */
        post: operations["bulkInventoryUpdate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory/{restaurant_id}/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Unique UFDS restaurant identifier.
                 * @example RST-IN-MH-001
                 */
                restaurant_id: components["parameters"]["restaurantId"];
                /**
                 * @description Menu item identifier.
                 * @example ITEM-001
                 */
                item_id: components["parameters"]["itemId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Toggle single item availability */
        patch: operations["updateItemAvailability"];
        trace?: never;
    };
    "/analytics/{restaurant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Unique UFDS restaurant identifier.
                 * @example RST-IN-MH-001
                 */
                restaurant_id: components["parameters"]["restaurantId"];
            };
            cookie?: never;
        };
        /**
         * Unified cross-platform analytics
         * @description Returns aggregated business metrics for the restaurant across all
         *     connected platforms for the requested time period.
         */
        get: operations["getAnalytics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/order.new": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * [Inbound] New order received
         * @description UFDS delivers this payload to your registered webhook URL when a new
         *     order arrives from any platform. Respond with HTTP 200 within 5 seconds.
         *     Failed deliveries are retried up to 3 times with exponential backoff.
         *
         *     Verify the `X-UFDS-Signature` header (HMAC-SHA256 of the raw body
         *     using your webhook secret) before processing.
         */
        post: operations["webhookOrderNew"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/order.status_update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * [Inbound] Order status changed
         * @description Delivered when the originating platform updates an order's status
         *     (e.g. rider assigned, order picked up).
         */
        post: operations["webhookOrderStatusUpdate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/order.cancelled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** [Inbound] Order cancelled */
        post: operations["webhookOrderCancelled"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/platform.offline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * [Inbound] Platform unreachable
         * @description Fired when UFDS cannot reach a connected delivery platform.
         *     Use this to display a warning in your kitchen dashboard.
         */
        post: operations["webhookPlatformOffline"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/menu.sync_failed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** [Inbound] Menu sync failed on a platform */
        post: operations["webhookMenuSyncFailed"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Every response is wrapped in this envelope. */
        UFDSEnvelope: {
            /** @example 1.0 */
            ufds_version: string;
            /**
             * Format: date-time
             * @example 2026-06-16T12:45:00Z
             */
            timestamp: string;
        };
        ErrorResponse: {
            error: {
                /** @example UFDS_4022 */
                code: string;
                /** @enum {string} */
                category: "AUTH" | "VALIDATION" | "STATE" | "PLATFORM" | "INTERNAL";
                /** @example item_id ITEM-099 not found in menu for RST-IN-MH-001 */
                message: string;
                /**
                 * @description Dot-path to the offending field, if applicable.
                 * @example items[1].item_id
                 */
                field?: string;
                /**
                 * Format: uri
                 * @example https://ufds.dev/errors/4022
                 */
                docs?: string;
            };
        };
        /**
         * @description - `VEG` — Vegetarian (green dot)
         *     - `NON_VEG` — Non-vegetarian (brown dot)
         *     - `EGG` — Egg-based, no meat
         *     - `VEGAN` — No animal products
         * @enum {string}
         */
        FoodType: "VEG" | "NON_VEG" | "EGG" | "VEGAN";
        /**
         * @description Valid status transitions:
         *     `PENDING → ACCEPTED → PREPARING → READY → PICKED_UP → DELIVERED`
         *     Any state may transition to `CANCELLED` or `FAILED`.
         * @enum {string}
         */
        OrderStatus: "PENDING" | "ACCEPTED" | "PREPARING" | "READY" | "PICKED_UP" | "DELIVERED" | "CANCELLED" | "FAILED";
        /**
         * @description The originating delivery platform for an order.
         * @enum {string}
         */
        Platform: "swiggy" | "zomato" | "ondc" | "direct";
        /** @enum {string} */
        CancellationReason: "CUSTOMER_REQUEST" | "ITEM_UNAVAILABLE" | "RESTAURANT_CLOSED" | "RIDER_UNAVAILABLE" | "PAYMENT_FAILED" | "SYSTEM_ERROR";
        /** @enum {string} */
        UnavailabilityReason: "SOLD_OUT" | "PREP_UNAVAILABLE" | "SEASONAL";
        CustomisationOption: {
            /** @example OPT-001 */
            id: string;
            /** @example Hot */
            name: string;
            /**
             * Format: float
             * @description Price added (positive) or subtracted (negative) for this option.
             * @example 0
             */
            price_delta: number;
        };
        CustomisationGroup: {
            /** @example Spice Level */
            group: string;
            /** @example false */
            required: boolean;
            /**
             * @default 0
             * @example 0
             */
            min_select: number;
            /**
             * @default 1
             * @example 1
             */
            max_select: number;
            options: components["schemas"]["CustomisationOption"][];
        };
        MenuItem: {
            /** @example ITEM-001 */
            id: string;
            /** @example Paneer Tikka */
            name: string;
            /** @example Grilled cottage cheese with spices */
            description?: string;
            /**
             * Format: float
             * @example 280
             */
            base_price: number;
            /**
             * @default INR
             * @example INR
             */
            currency: string;
            food_type: components["schemas"]["FoodType"];
            /** @example true */
            available: boolean;
            customisations?: components["schemas"]["CustomisationGroup"][];
            /**
             * @example [
             *       "bestseller",
             *       "gluten-free"
             *     ]
             */
            tags?: string[];
            /** @example 15 */
            prep_time_minutes?: number;
            /**
             * Format: uri
             * @example https://cdn.example.com/items/paneer-tikka.jpg
             */
            image_url?: string;
        };
        MenuCategory: {
            /** @example CAT-001 */
            id: string;
            /** @example Starters */
            name: string;
            /** @example 1 */
            display_order: number;
            /** @example true */
            available: boolean;
            items: components["schemas"]["MenuItem"][];
        };
        Menu: components["schemas"]["UFDSEnvelope"] & {
            /** @example RST-IN-MH-001 */
            restaurant_id: string;
            menu: {
                /**
                 * Format: date-time
                 * @example 2026-06-16T10:30:00Z
                 */
                last_updated: string;
                categories: components["schemas"]["MenuCategory"][];
            };
        };
        Address: {
            /** @example Flat 4B, Prestige Towers, Banjara Hills, Hyderabad 500034 */
            full?: string;
            /**
             * Format: double
             * @example 17.385
             */
            lat?: number;
            /**
             * Format: double
             * @example 78.486
             */
            lng?: number;
        };
        Customer: {
            /** @example Priya Sharma */
            name: string;
            /**
             * @description Masked after T+30 days per UFDS data retention policy.
             * @example +91XXXXXXXXXX
             */
            phone?: string;
            address?: components["schemas"]["Address"];
        };
        OrderItemCustomisation: {
            /** @example Spice Level */
            group: string;
            /** @example Hot */
            selected: string;
        };
        OrderItem: {
            /** @example ITEM-001 */
            item_id: string;
            /** @example Paneer Tikka */
            name: string;
            /** @example 2 */
            quantity: number;
            /**
             * Format: float
             * @example 280
             */
            unit_price: number;
            customisations?: components["schemas"]["OrderItemCustomisation"][];
            /**
             * Format: float
             * @example 560
             */
            total_price: number;
        };
        OrderPricing: {
            /**
             * Format: float
             * @example 560
             */
            subtotal: number;
            /**
             * Format: float
             * @example 50.4
             */
            taxes: number;
            /**
             * Format: float
             * @example 40
             */
            delivery_fee: number;
            /**
             * Format: float
             * @example 0
             */
            discount: number;
            /**
             * Format: float
             * @example 650.4
             */
            total: number;
            /**
             * @default INR
             * @example INR
             */
            currency: string;
            /**
             * @example PREPAID
             * @enum {string}
             */
            payment_status: "PREPAID" | "COD" | "PENDING";
        };
        OrderTimestamps: {
            /**
             * Format: date-time
             * @example 2026-06-16T12:44:50Z
             */
            placed: string;
            /**
             * Format: date-time
             * @example 2026-06-16T12:45:30Z
             */
            accepted?: string | null;
            /**
             * Format: date-time
             * @example null
             */
            ready?: string | null;
            /**
             * Format: date-time
             * @example null
             */
            picked_up?: string | null;
            /**
             * Format: date-time
             * @example null
             */
            delivered?: string | null;
        };
        OrderSource: {
            platform: components["schemas"]["Platform"];
            /** @example SWG-993847123 */
            platform_order_id: string;
            /**
             * Format: date-time
             * @example 2026-06-16T12:45:00Z
             */
            received_at: string;
        };
        Order: {
            /**
             * @description UFDS-assigned canonical order ID.
             * @example UFDS-ORD-20260616-00142
             */
            id: string;
            source: components["schemas"]["OrderSource"];
            /** @example RST-IN-MH-001 */
            restaurant_id: string;
            status: components["schemas"]["OrderStatus"];
            customer: components["schemas"]["Customer"];
            items: components["schemas"]["OrderItem"][];
            pricing: components["schemas"]["OrderPricing"];
            timestamps: components["schemas"]["OrderTimestamps"];
            cancellation_reason?: components["schemas"]["CancellationReason"];
            /** @example Please keep it less spicy */
            special_instructions?: string;
        };
        OrderResponse: components["schemas"]["UFDSEnvelope"] & {
            order: components["schemas"]["Order"];
        };
        OrderListResponse: components["schemas"]["UFDSEnvelope"] & {
            orders: components["schemas"]["Order"][];
            pagination: {
                /** @example 148 */
                total?: number;
                /** @example 1 */
                page?: number;
                /** @example 20 */
                per_page?: number;
                /** @example eyJpZCI6Ijk5In0= */
                next_cursor?: string | null;
            };
        };
        OrderStatusUpdate: {
            status: components["schemas"]["OrderStatus"];
            cancellation_reason?: components["schemas"]["CancellationReason"];
            /**
             * @description Estimated minutes until READY (used when transitioning to PREPARING).
             * @example 18
             */
            eta_minutes?: number;
        };
        InventoryItem: {
            /** @example ITEM-001 */
            item_id: string;
            /** @example false */
            available: boolean;
            /**
             * @description Absolute count; null means unlimited.
             * @example null
             */
            stock_count?: number | null;
            reason?: components["schemas"]["UnavailabilityReason"];
        };
        InventoryUpdate: components["schemas"]["UFDSEnvelope"] & {
            /** @example RST-IN-MH-001 */
            restaurant_id: string;
            items: components["schemas"]["InventoryItem"][];
        };
        PlatformMetrics: {
            /** @example 412 */
            orders?: number;
            /**
             * Format: float
             * @example 182400
             */
            revenue_inr?: number;
            /**
             * Format: float
             * @example 443
             */
            avg_order_value?: number;
        };
        TopItem: {
            /** @example ITEM-001 */
            item_id?: string;
            /** @example Paneer Tikka */
            name?: string;
            /** @example 340 */
            orders?: number;
            /**
             * Format: float
             * @example 95200
             */
            revenue?: number;
        };
        AnalyticsResponse: components["schemas"]["UFDSEnvelope"] & {
            analytics: {
                /** @example RST-IN-MH-001 */
                restaurant_id?: string;
                period?: {
                    /**
                     * Format: date
                     * @example 2026-06-01
                     */
                    from?: string;
                    /**
                     * Format: date
                     * @example 2026-06-15
                     */
                    to?: string;
                };
                /**
                 * @example {
                 *       "swiggy": {
                 *         "orders": 412,
                 *         "revenue_inr": 182400,
                 *         "avg_order_value": 443
                 *       },
                 *       "zomato": {
                 *         "orders": 298,
                 *         "revenue_inr": 134100,
                 *         "avg_order_value": 450
                 *       }
                 *     }
                 */
                by_platform?: {
                    [key: string]: components["schemas"]["PlatformMetrics"];
                };
                top_items?: components["schemas"]["TopItem"][];
                /**
                 * Format: float
                 * @example 18
                 */
                avg_prep_time_minutes?: number;
                /**
                 * Format: float
                 * @example 2.4
                 */
                cancellation_rate_pct?: number;
            };
        };
        WebhookOrderNew: components["schemas"]["UFDSEnvelope"] & {
            /** @enum {string} */
            event: "order.new";
            order: components["schemas"]["Order"];
        };
        WebhookOrderStatusUpdate: components["schemas"]["UFDSEnvelope"] & {
            /** @enum {string} */
            event: "order.status_update";
            /** @example UFDS-ORD-20260616-00142 */
            order_id: string;
            status: components["schemas"]["OrderStatus"];
            cancellation_reason?: components["schemas"]["CancellationReason"];
        };
        WebhookOrderCancelled: components["schemas"]["UFDSEnvelope"] & {
            /** @enum {string} */
            event: "order.cancelled";
            /** @example UFDS-ORD-20260616-00142 */
            order_id: string;
            reason: components["schemas"]["CancellationReason"];
        };
        WebhookPlatformOffline: components["schemas"]["UFDSEnvelope"] & {
            /** @enum {string} */
            event: "platform.offline";
            platform: components["schemas"]["Platform"];
            /** @example Swiggy Partner API returning 503 — retrying. */
            message?: string;
        };
        WebhookMenuSyncFailed: components["schemas"]["UFDSEnvelope"] & {
            /** @enum {string} */
            event: "menu.sync_failed";
            platform: components["schemas"]["Platform"];
            /** @example RST-IN-MH-001 */
            restaurant_id: string;
            /** @example Platform rejected menu — invalid category ID format. */
            reason?: string;
        };
    };
    responses: {
        /** @description Missing or invalid bearer token. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "UFDS_4001",
                 *         "category": "AUTH",
                 *         "message": "Missing or invalid bearer token.",
                 *         "docs": "https://ufds.dev/errors/4001"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Request payload failed validation. */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Rate limit exceeded. */
        RateLimited: {
            headers: {
                /** @description Seconds until the rate limit resets. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /**
         * @description Unique UFDS restaurant identifier.
         * @example RST-IN-MH-001
         */
        restaurantId: string;
        /**
         * @description UFDS canonical order ID.
         * @example UFDS-ORD-20260616-00142
         */
        orderId: string;
        /**
         * @description Menu item identifier.
         * @example ITEM-001
         */
        itemId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMenu: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Unique UFDS restaurant identifier.
                 * @example RST-IN-MH-001
                 */
                restaurant_id: components["parameters"]["restaurantId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Menu retrieved successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Menu"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    replaceMenu: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Unique UFDS restaurant identifier.
                 * @example RST-IN-MH-001
                 */
                restaurant_id: components["parameters"]["restaurantId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Menu"];
            };
        };
        responses: {
            /** @description Menu replaced and sync initiated on all platforms. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Menu"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
        };
    };
    deleteMenuItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Unique UFDS restaurant identifier.
                 * @example RST-IN-MH-001
                 */
                restaurant_id: components["parameters"]["restaurantId"];
                /**
                 * @description Menu item identifier.
                 * @example ITEM-001
                 */
                item_id: components["parameters"]["itemId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Item removed successfully. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateMenuItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Unique UFDS restaurant identifier.
                 * @example RST-IN-MH-001
                 */
                restaurant_id: components["parameters"]["restaurantId"];
                /**
                 * @description Menu item identifier.
                 * @example ITEM-001
                 */
                item_id: components["parameters"]["itemId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MenuItem"];
            };
        };
        responses: {
            /** @description Item updated and synced. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuItem"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listOrders: {
        parameters: {
            query?: {
                /** @description Filter by order status. */
                status?: components["schemas"]["OrderStatus"];
                /** @description Filter by source platform. */
                platform?: components["schemas"]["Platform"];
                /**
                 * @description Start date (inclusive).
                 * @example 2026-06-01
                 */
                from?: string;
                /**
                 * @description End date (inclusive).
                 * @example 2026-06-16
                 */
                to?: string;
                page?: number;
                per_page?: number;
            };
            header?: never;
            path: {
                /**
                 * @description Unique UFDS restaurant identifier.
                 * @example RST-IN-MH-001
                 */
                restaurant_id: components["parameters"]["restaurantId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Order list returned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
        };
    };
    getOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Unique UFDS restaurant identifier.
                 * @example RST-IN-MH-001
                 */
                restaurant_id: components["parameters"]["restaurantId"];
                /**
                 * @description UFDS canonical order ID.
                 * @example UFDS-ORD-20260616-00142
                 */
                order_id: components["parameters"]["orderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Order retrieved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateOrderStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Unique UFDS restaurant identifier.
                 * @example RST-IN-MH-001
                 */
                restaurant_id: components["parameters"]["restaurantId"];
                /**
                 * @description UFDS canonical order ID.
                 * @example UFDS-ORD-20260616-00142
                 */
                order_id: components["parameters"]["orderId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderStatusUpdate"];
            };
        };
        responses: {
            /** @description Status updated and propagated to platform. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description Invalid status transition. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "UFDS_4030",
                     *         "category": "STATE",
                     *         "message": "Cannot transition from DELIVERED to PREPARING.",
                     *         "docs": "https://ufds.dev/errors/4030"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    simulateOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Unique UFDS restaurant identifier.
                 * @example RST-IN-MH-001
                 */
                restaurant_id: components["parameters"]["restaurantId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    platform?: components["schemas"]["Platform"];
                    /**
                     * @example [
                     *       "ITEM-001",
                     *       "ITEM-012"
                     *     ]
                     */
                    item_ids?: string[];
                };
            };
        };
        responses: {
            /** @description Simulated order created and webhook fired. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"];
                };
            };
            /** @description Simulation not available in production. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    bulkInventoryUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Unique UFDS restaurant identifier.
                 * @example RST-IN-MH-001
                 */
                restaurant_id: components["parameters"]["restaurantId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "ufds_version": "1.0",
                 *       "timestamp": "2026-06-16T13:00:00Z",
                 *       "restaurant_id": "RST-IN-MH-001",
                 *       "items": [
                 *         {
                 *           "item_id": "ITEM-001",
                 *           "available": true,
                 *           "stock_count": null
                 *         },
                 *         {
                 *           "item_id": "ITEM-005",
                 *           "available": false,
                 *           "reason": "SOLD_OUT"
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["InventoryUpdate"];
            };
        };
        responses: {
            /** @description Inventory synced to all connected platforms. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ufds_version?: string;
                        /**
                         * @example [
                         *       "swiggy",
                         *       "zomato",
                         *       "ondc"
                         *     ]
                         */
                        synced_platforms?: string[];
                        /** @example [] */
                        failed_platforms?: string[];
                    };
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
        };
    };
    updateItemAvailability: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Unique UFDS restaurant identifier.
                 * @example RST-IN-MH-001
                 */
                restaurant_id: components["parameters"]["restaurantId"];
                /**
                 * @description Menu item identifier.
                 * @example ITEM-001
                 */
                item_id: components["parameters"]["itemId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InventoryItem"];
            };
        };
        responses: {
            /** @description Item availability updated across all platforms. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InventoryItem"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getAnalytics: {
        parameters: {
            query: {
                /** @example 2026-06-01 */
                from: string;
                /** @example 2026-06-15 */
                to: string;
                /** @description Filter to a single platform (omit for all). */
                platform?: components["schemas"]["Platform"];
            };
            header?: never;
            path: {
                /**
                 * @description Unique UFDS restaurant identifier.
                 * @example RST-IN-MH-001
                 */
                restaurant_id: components["parameters"]["restaurantId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Analytics data returned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
        };
    };
    webhookOrderNew: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["WebhookOrderNew"];
            };
        };
        responses: {
            /** @description Acknowledged. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    webhookOrderStatusUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["WebhookOrderStatusUpdate"];
            };
        };
        responses: {
            /** @description Acknowledged. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    webhookOrderCancelled: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["WebhookOrderCancelled"];
            };
        };
        responses: {
            /** @description Acknowledged. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    webhookPlatformOffline: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["WebhookPlatformOffline"];
            };
        };
        responses: {
            /** @description Acknowledged. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    webhookMenuSyncFailed: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["WebhookMenuSyncFailed"];
            };
        };
        responses: {
            /** @description Acknowledged. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
